name: Build And Release
on:
  push:
    tags:
      v*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: Translumo.sln
      SkipBinariesExtract: true
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
  
      - name: Build the application
        run: dotnet build $env:Solution_Name /p:Configuration=Release
  
      - name: Publish the application
        run: dotnet publish src\Translumo\Translumo.csproj --no-build -c Release -o .\dist
        
      - name: extract binary
        run: cmd /c binaries_extract.bat ".\dist"
  
      - name: Release the application
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Translumo-VideoOCR.zip'
          directory: dist